language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: JuIiVuWh1KgB6AIOmuyIXdJKcuIa7o1mc5gQow8X+beOk9cZM5Z3WBDw7umfqtuLvER3hmT+zRFVSQmDyQ+4TQ32rjz372qQi03pKs81nog1NS1ZwNI2teDB+nMF4RL2MMA08kBwBsKq2/AkBYpnMogOfWVgkY9y5SXLYfxNXl7384oRR3N3FN92sFqh0N+IsI84xohT5ozA/amhAgDMbxzfANNrQrvAO9+W4rj84Z+P7ASqoZoWPb7QZokOnmJhm8qb5CMauIS7dtmSlZWc2M613g27CkQ0aW62TSDEFGTvXynbEE2lwyR2eRDFOboKioYf3vepcE8NK665zf8CR4AfpJqg2BNn1CQQLMXOk0HJTvmmq0W5QtVnLEwtoTk/vZewitqruEHVfFw9JWIvZNsdUmb2ppz6umA6RhqqIYG/bzXMQKuwkAMtz9itiCvzCcEQf7BdHtEXu99bmu5JMwoOWSG3q1uNVeZ6BNhhrl5aeO1sEbP/7n47n/DJ7VEnQztU/nBuCelhx3dpEK2ltOFLks/O+T8+4RMXynq6mzkcO87SWEUCBlu6wAz6LZko90qIlBMOJUqJukyQVAyHytTXmXWIVIu1l67hVeLK0bVBmhtOqdsvmb8x0cRDsZejDnnLxGrh41GlrsjdUQDHr75HVdyUL25hSVOFBUWU5gw=
  app: pure-peak-20096
  on:
    repo: ispoljari/run-tracker-app
  
branches:
  only:
    - master