language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: vdithug7t0n6jFwIlonnNgjn5fuiDBprar5bk9Mq0686pnG/pw15i/3hdmmJy/A5upqQ6wTaXOa43cS0ypLG0jqVp5O9trdbxi5h5KoRMjaXdqAbeYTvUmbDfso14hqGKYgFebRg5CAqV14SxN++sXupTinRpyLh54obuf1W7A9zNnxEgsAW3GGzXvZUEXm7zBO8EJemwqAcRHe9Nymq3X+kmKUsPGXx0pq/s3n1hNF70WVpTRg1YC8wtCAB4xb8zn9wjtHkWxkyrMW3UtgnpYWhZK6CzngBYB3HkZjq+ALr/88gj4pIA1C4LXjTpF38olIfXBk5501LKyxncxEvqeEf2tSaG5smB8bItUdC1ZzB6SZpo2KZMszEUqCGHyuuTL1sMBFbyZdvaFIsYzc93O6mQ8I2ZU400TJPCdxTw/vMPJCdCupIJb68PqDEcC0yEHvzTr4+yOc6s5xaJU7xGsWyZ9xfpq1w1VJMCzW2JihoAuOGzSH/RuZYyziOOx8X5xjIyuE8+f91ocH0fX9ARz3bbkp5E9nZvj7rvKHvnmPwl0JuWjWS/3mKdGdUp4+2/gEjFqvgzL4NYzJV41EGmFaxgSv6ZEcX9la3Rl9FXfmSetMpSlpVsbAN2rTdvsHzPChnDAsNTeDHbIGRxLUkrO7+kSWLdS84HzTv6iLTz5Y=
  app: fathomless-citadel-59742
  on:
    repo: ispoljari/run-tracker-app
