language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: l3nsEsomcr7nvr06kQOeBFZ9/CpPXVpFOXZ2l+swizdOvJGn4EHuNg4uOC2GPqEkANa951eix3yYrvl5LCJV5LVySIcPulIVM3Rq16XHaWHtTufqLYj9f2gFE+x9sWGVeVo9udKZQrHvVtaIMwR3sPiyDP4sr/1XJiyiEs75XkVZChJDScHDpsXbvn9ARu0y6QpBb2wYTtUSA7/IsdcAVKMSTs/THe/W4lsd987yG/ga8S4Tv+xDIGX46Ax5tWT7VzhHTLPQc58WBNnidzoWDDPhy9R/SABam7C+d2cOCGXvLIaT/y6i8RBMI1evpf7j/zzEyxzP1K8EYQ6mNRksvpFdg9a8+wWIti6OKsOuqgd+YeCzL/SPyhEwNTI+qef5q7GDZDQQ+Rbame4RANnE5C+j4vX0qnDsPr3AWX+rexdL2QXiTdSmfyTtE5WEQCnq2d/BuYnBk2Wx5UyHXuCLRUJptI69OXGnej8MJANbgpW3v4QHJEs1kJfZXl48g1r6mjNFtPWckHdsZtzwPMH95O4j6c1+t0XfO2yyJ6bp1sPp0DZgkn4/ZjcSS4BgWAtvzvuwIg6YBB0ZNnv5x6v5OGICFfu1pXV+41KjYH6L4pKKnnrrh9hix/NAVIPc28VxLwiPw/F8tTHnt3h2AQQ1Zp2AtK36uRJ9ojj09dil9QQ=
  app: pure-peak-20096
  on:
    repo: ispoljari/run-tracker-app
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_bf2abbc3aa7a_key -iv $encrypted_bf2abbc3aa7a_iv
  -in .env.enc -out .env -d
